#!/usr/bin/env bash
set -eux

pwd
ls -la
ls -la "${REPO_DIR:-/home/jovyan/src}"

pip install -e "${REPO_DIR:-/home/jovyan/src}"

# python -c "import binder_launcher; print(binder_launcher.__file__)"
jupyter server extension enable --py binder_launcher --sys-prefix
jupyter server extension list
